### ISSUE TITLE
Vidz not playing

### ISSUE THREAD

**Issue by danhearn** [danhearn/transforming-collections#23]
Hi @lukeplowden , 

rly rly sorry but it's me again! 

Erika has given me a new bunch of final videos. I think she might have compressed them and they are also landscape now. Not sure if that changes anything but worth mentioning. 

Anyway I've made a new dataset with the videos in and when I run the main program I get this error:  

`found media GIF Shaman Shaman 1.mp4
Received instruction to play: GIF Shaman Shaman 1.mp4
Error in Media Player's run method: 'GIF Shaman Shaman 1.mp4'
Window terminated.`

If you take a look at the dataset-with-media branch you'll be able to run with thethe new dataset.

Here is the retransfer to the vids: https://wetransfer.com/downloads/ca34960e5ee440d1b48851ee687f5e2720240903134132/0c3f1f45adfa26b99028904dda56d03520240903134148/b01978?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

lmk if you can look into this or if you need anything else 

Very sorry and thanks again! :D

**Comment by lukeplowden** [comment]
No problem! The issue was [here](https://github.com/danhearn/transforming-collections/blob/42c7025a7e096fd28183e02567c8245549a500e9/installation-application/media.py#L9C8-L9C33).

I've changed that line to:
```python
self.ID = self.path.name
```
But now the CSV dataset should always contain the file extension if any new vids are added. In testing we were working with CSV which said gif-1,gif-2 etc not gif-1.gif. 

Otherwise we can rename the csv files to remove extensions! GIF Wellcome archives 3.mp4 -> GIF Wellcome archives 3

It's fixed now though :troll:

**Comment by danhearn** [comment]
ok thanks! That was actually pretty stupid of me lol serves me right for working on it late
